name: publish nuget

on:
  push:
    branches: [ main ]

jobs:
  Publish-NuGet-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: .github/GitVersion.yml

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack FunctionsAttributes
      run: dotnet pack src/FunctionsAttributes/FunctionsAttributes.csproj --no-restore

    - name: Push FunctionsAttributes
      run: dotnet nuget push src/FunctionsAttributes/**/*.nupkg --api-key ${{ secrets.API_KEY }} --source https://api.nuget.org/v3/index.json
